version: "3.9"
services:
  pet_care_alimentation:
    build: ./pet_care_alimentation
    image: "alimentation"
    container_name: alimentationContainer
    ports:
      - "8091:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/petcare_alimentation_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    depends_on:
      - eureka
      - mysql-db

  pet_care_service:
    build: ./Pet_Care_Service
    image: "service"
    container_name: serviceContainer
    ports:
      - "8093:8092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/petcaredb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root 
    restart: unless-stopped
    depends_on:
      - eureka
      - mysql-db

  eureka:
    build: ./Eureka
    image: "eureka"
    container_name: "eurekaContainer"
    ports:
      - "8762:8761"
    hostname: discovery

  gateway:
    build: ./ApiGateway
    image: "apigateway"
    container_name: "apigatewayContainer"
    ports:
      - "8083:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8762/eureka
      - spring_cloud_gateway_routes[0]_id=service
      - spring_cloud_gateway_routes[0]_uri=http://service:8093
      - spring_cloud_gateway_routes[0]_predicates[0]=Path=/service/**
      - spring_cloud_gateway_routes[1]_id=alimentation
      - spring_cloud_gateway_routes[1]_uri=http://alimentation:8091
      - spring_cloud_gateway_routes[1]_predicates[0]=Path=/alimentation/**
    depends_on:
      - eureka
      - pet_care_alimentation
      - pet_care_service

  mysql-db:
    image: "mysql:5.6"
    container_name: "mysql-db"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
